FROM local_discourse/web_only

ADD ldap.rb /var/www/discourse/plugins/discourse-ldap-auth/gems/2.6.3/gems/omniauth-ldap-1.0.5/lib/omniauth/strategies/ldap.rb
ADD ldap_user.rb /var/www/discourse/plugins/discourse-ldap-auth/lib/ldap_user.rb
